[project]
name = "afc"
version = "0.5.0"
description = "Audio file converter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydub>=0.25.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
